<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE devices
[
        <!ELEMENT devices       (device+)>
        <!ELEMENT device        (name,hostname,ipaddress,port)>
        <!ELEMENT name          (#PCDATA)>
        <!ELEMENT hostname      (#PCDATA)>
        <!ELEMENT ipaddress     (#PCDATA)>
        <!ELEMENT port          (#PCDATA)>
]>

<devices>
    <device>
        <name>Edit 2 Google DNS A</name>
        <hostname>google-public-dns-a.google.com</hostname>
        <ipaddress>8.8.8.8</ipaddress>
        <port></port>
    </device>
    <device>
        <name>Edit 2 Google DNS B</name>
        <hostname>google-public-dns-b.google.com</hostname>
        <ipaddress>8.8.4.4</ipaddress>
        <port></port>
    </device>
</devices>
